version: '3.4'

services:
  gifbox-client:
    image: gifbox-client
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
